// Generates Git hooks and CI pipelines that call `bca run --trigger <name>`.
// The pipelines contain no BC Atlas logic of their own: what runs and how it
// is synced is configured once in .bca.json.
export const GENERATED_MARKER = "Generated by bca setup";

const PIPELINE_SYNC_CI = ["none", "verify", "artifact"];
const PIPELINE_SYNC_SCHEDULE = ["none", "verify", "artifact", "pull-request", "commit"];

export function validatePipelineSync(provider, ciSync, scheduleSync) {
  if (ciSync && !PIPELINE_SYNC_CI.includes(ciSync)) {
    throw new Error(`--ci-sync must be one of ${PIPELINE_SYNC_CI.join(", ")}`);
  }
  if (scheduleSync && !PIPELINE_SYNC_SCHEDULE.includes(scheduleSync)) {
    throw new Error(`--schedule-sync must be one of ${PIPELINE_SYNC_SCHEDULE.join(", ")}`);
  }
  if (provider === "azure-devops" && scheduleSync === "pull-request") {
    throw new Error("--schedule-sync pull-request is available for GitHub; use commit or artifact on Azure DevOps");
  }
}

function shellQuote(value) {
  return /^[\w./-]+$/u.test(value) ? value : `"${value.replaceAll("\"", "\\\"")}"`;
}

function yamlList(items, indent) {
  return items.map((item) => `${" ".repeat(indent)}${item}`).join("\n");
}

/** One line per hook, so existing hook files keep their other commands. */
export function hookCommand(manager, hook, { appPath, version }) {
  const args = `run ${shellQuote(appPath)} --trigger ${hook}`;
  if (manager === "husky") return `npx --no-install bca ${args} || exit 1`;
  return `if command -v bca >/dev/null 2>&1; then bca ${args} || exit 1; else npx --yes bc-atlas@${version} ${args} || exit 1; fi`;
}

/** Inserts or replaces the BC Atlas line in a hook script. */
export function mergeHook(existing, manager, hook, options) {
  const command = hookCommand(manager, hook, options);
  const lines = existing ? existing.replace(/\s+$/u, "").split("\n") : (manager === "git" ? ["#!/bin/sh"] : []);
  const index = lines.findIndex((line) => line.includes("bca") && line.includes(`--trigger ${hook}`));
  if (index >= 0) {
    lines[index] = command;
  } else {
    lines.push(`# BC Atlas (${GENERATED_MARKER})`, command);
  }
  return `${lines.join("\n")}\n`;
}

/** How pipelines start BC Atlas: the package.json version, or a pinned npx version. */
function runner({ version, local }) {
  return local ? "npx --no-install bca" : `npx --yes bc-atlas@${version}`;
}

export function githubWorkflow({ appPath, version, triggers, nodeVersion = 24, local = false, packageRoot = "." }) {
  const ci = triggers.ci;
  const schedule = triggers.schedule;
  const outputs = (trigger) => trigger?.outputs ?? [];
  const writes = schedule && ["pull-request", "commit"].includes(schedule.sync);
  const on = [];
  if (ci) on.push("  pull_request:", "  push:", "    branches: [main]");
  if (schedule?.cron) on.push("  schedule:", `    - cron: "${schedule.cron}"`);
  on.push("  workflow_dispatch:");
  const trigger = ci && schedule
    ? "${{ github.event_name == 'schedule' && 'schedule' || 'ci' }}"
    : schedule ? "schedule" : "ci";
  const steps = [
    "      - uses: actions/checkout@v4",
    "      - uses: actions/setup-node@v4",
    "        with:",
    `          node-version: ${nodeVersion}`,
    ...(local ? [
      "      - name: Install BC Atlas from package.json",
      "        run: if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi",
      ...(packageRoot === "." ? [] : [`        working-directory: ${packageRoot}`])
    ] : []),
    "      - name: Run BC Atlas",
    "        env:",
    `          BCA_TRIGGER: ${trigger}`,
    `        run: ${runner({ version, local })} run ${shellQuote(appPath)} --trigger "$BCA_TRIGGER"`
  ];
  const artifact = (condition, paths, name) => [
    `      - name: Upload ${name}`,
    `        if: always() && ${condition}`,
    "        uses: actions/upload-artifact@v4",
    "        with:",
    `          name: ${name}`,
    "          if-no-files-found: ignore",
    "          path: |",
    yamlList(paths, 12)
  ];
  if (ci?.sync === "artifact" && outputs(ci).length) {
    steps.push(...artifact("github.event_name != 'schedule'", outputs(ci), "bc-atlas"));
  }
  if (schedule?.sync === "artifact" && outputs(schedule).length) {
    steps.push(...artifact("github.event_name == 'schedule'", outputs(schedule), "bc-atlas-scheduled"));
  }
  if (schedule?.sync === "pull-request" && outputs(schedule).length) {
    steps.push(
      "      - name: Open a pull request with updated output",
      "        if: github.event_name == 'schedule'",
      "        uses: peter-evans/create-pull-request@v7",
      "        with:",
      "          branch: bc-atlas/update",
      "          delete-branch: true",
      "          commit-message: \"docs: update BC Atlas output\"",
      "          title: Update BC Atlas output",
      "          body: Generated by the scheduled BC Atlas run.",
      "          add-paths: |",
      yamlList(outputs(schedule), 12)
    );
  }
  if (schedule?.sync === "commit" && outputs(schedule).length) {
    steps.push(
      "      - name: Commit updated output",
      "        if: github.event_name == 'schedule'",
      "        run: |",
      "          git config user.name \"github-actions[bot]\"",
      "          git config user.email \"41898282+github-actions[bot]@users.noreply.github.com\"",
      `          git add --all -- ${outputs(schedule).map(shellQuote).join(" ")}`,
      "          git diff --cached --quiet || git commit -m \"docs: update BC Atlas output\"",
      "          git push"
    );
  }
  return [
    `# ${GENERATED_MARKER}. Change .bca.json or rerun "bca setup apply" instead of editing.`,
    "name: BC Atlas",
    "",
    "on:",
    ...on,
    "",
    "permissions:",
    `  contents: ${writes ? "write" : "read"}`,
    ...(schedule?.sync === "pull-request" ? ["  pull-requests: write"] : []),
    "",
    "concurrency:",
    "  group: bc-atlas-${{ github.ref }}",
    "  cancel-in-progress: true",
    "",
    "jobs:",
    "  bc-atlas:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    ...steps,
    ""
  ].join("\n");
}

export function azurePipeline({ appPath, version, triggers, nodeVersion = 24, local = false }) {
  const ci = triggers.ci;
  const schedule = triggers.schedule;
  const lines = [`# ${GENERATED_MARKER}. Change .bca.json or rerun "bca setup apply" instead of editing.`];
  if (ci) {
    lines.push("trigger:", "  branches:", "    include: [main]", "", "pr:", "  branches:", "    include: ['*']", "");
  } else {
    lines.push("trigger: none", "pr: none", "");
  }
  if (schedule?.cron) {
    lines.push(
      "schedules:",
      `  - cron: "${schedule.cron}"`,
      "    displayName: BC Atlas scheduled run",
      "    branches:",
      "      include: [main]",
      "    always: true",
      ""
    );
  }
  lines.push(
    "pool:",
    "  vmImage: ubuntu-latest",
    "",
    "steps:",
    "  - checkout: self",
    ...(schedule?.sync === "commit" ? ["    persistCredentials: true"] : []),
    "  - task: NodeTool@0",
    "    inputs:",
    `      versionSpec: ${nodeVersion}.x`,
    ...(local ? [
      "  - bash: if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi",
      "    displayName: Install BC Atlas from package.json"
    ] : []),
    "  - bash: |",
    "      if [ \"$BUILD_REASON\" = \"Schedule\" ]; then trigger=schedule; else trigger=ci; fi",
    `      ${runner({ version, local })} run ${shellQuote(appPath)} --trigger "$trigger"`,
    "    displayName: Run BC Atlas"
  );
  const publish = (trigger, condition, prefix) => {
    for (const output of trigger?.outputs ?? []) {
      lines.push(
        `  - publish: ${output}`,
        `    artifact: ${prefix}-${output.replace(/[^A-Za-z0-9]+/gu, "-").replace(/^-|-$/gu, "")}`,
        `    condition: and(succeededOrFailed(), ${condition})`
      );
    }
  };
  if (ci?.sync === "artifact") publish(ci, "ne(variables['Build.Reason'], 'Schedule')", "bc-atlas");
  if (schedule?.sync === "artifact") publish(schedule, "eq(variables['Build.Reason'], 'Schedule')", "bc-atlas-scheduled");
  if (schedule?.sync === "commit" && schedule.outputs?.length) {
    lines.push(
      "  - bash: |",
      "      git config user.name \"BC Atlas\"",
      "      git config user.email \"bc-atlas@users.noreply.dev.azure.com\"",
      `      git add --all -- ${schedule.outputs.map(shellQuote).join(" ")}`,
      "      git diff --cached --quiet || git commit -m \"docs: update BC Atlas output [skip ci]\"",
      "      git push origin \"HEAD:$BUILD_SOURCEBRANCH\"",
      "    displayName: Commit updated output",
      "    condition: and(succeeded(), eq(variables['Build.Reason'], 'Schedule'))"
    );
  }
  lines.push("");
  return lines.join("\n");
}

export const PIPELINE_FILES = Object.freeze({
  github: ".github/workflows/bc-atlas.yml",
  "azure-devops": "azure-pipelines.bc-atlas.yml"
});
