direction: right
title: "AL module architecture" {
  shape: text
  near: top-center
  style.font-size: 28
}

g0: "(modules)" {
  style.stroke-dash: 3
  n0: "module\nDemo.Operations" {
    shape: rectangle
    style.fill: "#E8ECF3"
    style.stroke: "#4E5D78"
  }
  n1: "module\nDemo.Sales" {
    shape: rectangle
    style.fill: "#E8ECF3"
    style.stroke: "#4E5D78"
  }
}

g0.n0 -> g0.n1: "uses (2)" {style.stroke-dash: 3}
g0.n0 -> g0.n1: "reads (1)"
