import fs from "node:fs/promises";
import path from "node:path";
import { REPORT_VIEWS, VIEWS } from "../capabilities.js";
import { createArchitectureModel } from "../architecture.js";
import { generateCodeGraph } from "../codegraph.js";
import { formatHealthMarkdown, healthResultLine } from "../health.js";
import { displayPath, resolveOutput, writeArchitecture } from "../output.js";
import { runHealthCheck } from "./check.js";

const VIEW_SUMMARIES = new Map(VIEWS);
const VIEW_TITLES = {
  project: "Project overview",
  module: "Modules",
  data: "Data model",
  contracts: "Contracts",
  events: "Events",
  ui: "User interface",
  call: "Call graph",
  workflow: "Workflows",
  boundary: "Boundaries",
  object: "Object"
};
const SHARED_OPTIONS = [
  "projectRoot", "config", "namespace", "type", "include", "exclude",
  "sourceUrl", "sourceRef", "sourcePathPrefix"
];

function selectedViews(value, configured) {
  const requested = value ?? configured ?? REPORT_VIEWS;
  const views = (Array.isArray(requested) ? requested : String(requested).split(","))
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean);
  const supported = new Set(REPORT_VIEWS.concat("call"));
  const invalid = views.filter((view) => !supported.has(view));
  if (invalid.length) {
    throw new Error(`report views must be chosen from ${[...supported].join(", ")}; unsupported: ${invalid.join(", ")}`);
  }
  if (!views.length) throw new Error("select at least one report view");
  return [...new Set(views)];
}

function relativeLink(file) {
  return file.split("/").map(encodeURIComponent).join("/");
}

function anchor(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "");
}

function renderReadme({ title, health, diagrams, codegraph, model, json, format, command }) {
  const { summary } = health;
  const app = summary.apps[0];
  const lines = [
    "<!-- Generated by BC Atlas. Do not edit; rerun the command below instead. -->",
    "",
    `# ${title}`,
    ""
  ];
  if (app) {
    lines.push(`**${app.name}**${app.version ? ` ${app.version}` : ""}${app.publisher ? ` by ${app.publisher}` : ""}`, "");
  }
  lines.push(
    "## At a glance",
    "",
    "| Files | Objects | Relationships | Unresolved | Cycles | Health |",
    "| --- | --- | --- | --- | --- | --- |",
    `| ${summary.files} | ${summary.objects} | ${summary.relationships} | ${summary.unresolved} | ${summary.cycles} | ${health.passed ? "Passed" : "Failed"} (${health.counts.error} errors, ${health.counts.warning} warnings) |`,
    "",
    "## Contents",
    ""
  );
  for (const diagram of diagrams) lines.push(`- [${diagram.title}](#${anchor(diagram.title)})`);
  lines.push("- [Architecture health](#architecture-health)");
  if (codegraph) lines.push(`- [Object catalog](${relativeLink(codegraph.link)}) - ${codegraph.objects} object pages`);
  if (json) lines.push("- [Resolved model (JSON)](model.json)");
  lines.push("");

  for (const diagram of diagrams) {
    lines.push(`## ${diagram.title}`, "", `${diagram.summary}.`, "");
    if (diagram.skipped) {
      lines.push(`_Not rendered: ${diagram.skipped}_`, "");
      continue;
    }
    if (format === "svg") lines.push(`![${diagram.title}](${relativeLink(diagram.svg)})`, "");
    lines.push(
      `${diagram.nodes} nodes, ${diagram.edges} edges. Source: [${diagram.d2}](${relativeLink(diagram.d2)})`,
      ""
    );
  }

  lines.push(formatHealthMarkdown(health, { heading: "## Architecture health" }));
  lines.push(
    "## Regenerate",
    "",
    "```sh",
    command,
    "```",
    "",
    `_${model.files} AL file(s) analyzed. ${healthResultLine(health)}._`,
    ""
  );
  return lines.join("\n");
}

function commandLine(input, values) {
  const parts = ["bca", "report", input];
  if (values.outputDir) parts.push("--output-dir", values.outputDir);
  if (values.views) parts.push("--views", values.views);
  if (values.format && values.format !== "svg") parts.push("--format", values.format);
  if (values.codegraph) parts.push("--codegraph");
  if (values.json) parts.push("--json");
  return parts.map((part) => (/^[\w./:@,=-]+$/u.test(part) ? part : `"${part.replaceAll("\"", "\\\"")}"`)).join(" ");
}

/** Generates README.md, diagrams, and optional catalogs for one AL project. */
export async function generateReport(input, values = {}, { log = () => {} } = {}) {
  const cache = new Map();
  const shared = Object.fromEntries(SHARED_OPTIONS.filter((name) => values[name] !== undefined).map((name) => [name, values[name]]));
  const { architecture, report: health } = await runHealthCheck(input, shared, { cache });
  const configured = architecture.options.report ?? {};
  const outputDirectory = path.resolve(values.outputDir ?? configured.outputDir ?? "docs/atlas");
  const format = values.format ?? configured.format ?? "svg";
  if (!["svg", "d2"].includes(format)) throw new Error("report format must be svg or d2");
  const views = selectedViews(values.views, configured.views);
  const title = values.title ?? configured.title ??
    `${health.summary.apps[0]?.name ?? path.basename(path.resolve(input))} architecture`;
  await fs.mkdir(outputDirectory, { recursive: true });

  const diagrams = [];
  for (const view of views) {
    const diagram = { view, title: VIEW_TITLES[view], summary: VIEW_SUMMARIES.get(view), d2: `${view}.d2`, svg: `${view}.svg` };
    diagrams.push(diagram);
    try {
      const projection = await createArchitectureModel(input, {
        ...shared,
        view,
        title: `${title}: ${VIEW_TITLES[view]}`
      }, { cache });
      if (!projection.model.objects.length) {
        diagram.skipped = projection.model.emptyMessage ?? "no matching objects";
        await fs.rm(path.join(outputDirectory, diagram.d2), { force: true });
        await fs.rm(path.join(outputDirectory, diagram.svg), { force: true });
        continue;
      }
      const target = resolveOutput({ output: path.join(outputDirectory, `${view}.${format}`), format });
      await writeArchitecture(projection, target);
      diagram.nodes = projection.model.objects.length;
      diagram.edges = projection.model.edges.length;
      log(`Rendered ${view} view (${diagram.nodes} nodes, ${diagram.edges} edges)`);
    } catch (error) {
      diagram.skipped = error.message;
      log(`Skipped ${view} view: ${error.message}`);
    }
  }

  let codegraph;
  if (values.codegraph ?? configured.codegraph) {
    const result = await generateCodeGraph(input, {
      ...shared,
      outputDir: path.join(outputDirectory, "objects")
    });
    codegraph = { objects: result.objects, link: "objects/index.md" };
    log(`Generated ${result.objects} object page(s)`);
  }

  const json = values.json ?? configured.json ?? false;
  if (json) {
    await fs.writeFile(path.join(outputDirectory, "model.json"), `${JSON.stringify(architecture.model, null, 2)}\n`);
  }

  const readme = path.join(outputDirectory, "README.md");
  const displayValues = { ...values, outputDir: displayPath(outputDirectory) };
  await fs.writeFile(readme, renderReadme({
    title,
    health,
    diagrams,
    codegraph,
    model: architecture.model,
    json,
    format,
    command: commandLine(displayPath(path.resolve(input)), displayValues)
  }));
  return { outputDirectory, readme, health, diagrams, codegraph };
}

export async function reportCommand(input, values) {
  const result = await generateReport(input, values, { log: (message) => console.log(message) });
  const rendered = result.diagrams.filter(({ skipped }) => !skipped).length;
  console.log(healthResultLine(result.health));
  console.log(`Wrote ${displayPath(result.readme)} with ${rendered} diagram(s)`);
}
