import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import process from "node:process";

import { createCapabilities } from "../src/capabilities.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const docsRoot = path.join(root, "docs");
const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
const capabilities = createCapabilities(packageJson.version);

const sections = [
  ["Start here", [
    ["Getting started", "getting-started.md"],
    ["Architecture diagrams", "architecture-diagrams.md"],
    ["Configuration", "configuration.md"]
  ]],
  ["User documentation", [
    ["Documentation from AL UI tests", "al-ui-test-documentation.md"],
    ["Control Center", "control-center.md"],
    ["Automation and CI", "automation-and-ci.md"]
  ]],
  ["Integration and support", [
    ["Agent integration", "agent-integration.md"],
    ["MCP JSON example", "examples/mcp.json"],
    ["Troubleshooting", "troubleshooting.md"]
  ]],
  ["Reference", [
    ["CLI reference", "cli-reference.md"],
    ["Generated CLI capabilities", "reference/cli-capabilities.md"],
    ["UI-test documentation roadmap", "ui-test-documentation-roadmap.md"]
  ]],
  ["Generated examples", [
    ["Generated documentation catalog", "generated/index.md"]
  ]]
];

const toc = [
  "# BC Atlas documentation",
  "",
  "Use this table of contents to install, configure, and operate BC Atlas.",
  "The generated CLI capability reference comes directly from the source code.",
  ""
];

for (const [heading, entries] of sections) {
  toc.push(`## ${heading}`, "");
  for (const [label, relativePath] of entries) {
    if (relativePath !== "reference/cli-capabilities.md") {
      await readFile(path.join(docsRoot, relativePath));
    }
    toc.push(`- [${label}](./${relativePath.replaceAll("\\", "/")})`);
  }
  toc.push("");
}

const graph = capabilities.commands.find(({ id }) => id === "graph");
const commands = capabilities.commands.map(({ id, argv, purpose }) =>
  `| \`${id}\` | \`${argv.join(" ")}\` | ${purpose} |`
);
const views = graph.options.view.enum.map((view) => `- \`${view}\``);
const formats = graph.options.format.enum.map((format) => `- \`${format}\``);

const capabilityReference = [
  "# Generated CLI capabilities",
  "",
  "<!-- Generated by scripts/generate-docs.js. Do not edit this file. -->",
  "",
  `This page describes BC Atlas ${capabilities.version}.`,
  "Run `npm run docs` after a capability changes.",
  "",
  "## Commands",
  "",
  "| ID | Invocation | Purpose |",
  "| --- | --- | --- |",
  ...commands,
  "",
  "## Architecture views",
  "",
  ...views,
  "",
  "## Output formats",
  "",
  ...formats,
  "",
  "## Exit codes",
  "",
  `- Success: \`${capabilities.exitCodes.success}\``,
  `- Operation failure: \`${capabilities.exitCodes.operation}\``,
  `- Usage error: \`${capabilities.exitCodes.usage}\``,
  "",
  "For all options and examples, read the [CLI reference](../cli-reference.md).",
  ""
].join("\n");

const outputs = new Map([
  [path.join(docsRoot, "_TOC_.md"), toc.join("\n")],
  [path.join(docsRoot, "reference", "cli-capabilities.md"), capabilityReference]
]);

const check = process.argv.includes("--check");
for (const [file, content] of outputs) {
  if (check) {
    const current = await readFile(file, "utf8").catch(() => "");
    if (current !== content) {
      console.error(`${path.relative(root, file)} is out of date. Run npm run docs.`);
      process.exitCode = 1;
    }
    continue;
  }

  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, content, "utf8");
  console.log(`Wrote ${path.relative(root, file)}`);
}
