import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import process from "node:process";

import { createCapabilities } from "../src/capabilities.js";
import { SECTIONS, WEBSITE } from "./docs-structure.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const docsRoot = path.join(root, "docs");
const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
const capabilities = createCapabilities(packageJson.version);

const sections = SECTIONS;

const toc = [
  "# BC Atlas documentation",
  "",
  "BC Atlas is organized into five feature areas: get started, visualize,",
  "analyze, document, and integrate. This table of contents follows the same",
  "structure. The generated CLI capability reference comes directly from the",
  "source code.",
  "",
  `Read it online at ${WEBSITE}.`,
  ""
];

for (const [heading, entries] of sections) {
  toc.push(`## ${heading}`, "");
  for (const [label, relativePath] of entries) {
    if (relativePath !== "reference/cli-capabilities.md") {
      await readFile(path.join(docsRoot, relativePath));
    }
    toc.push(`- [${label}](./${relativePath.replaceAll("\\", "/")})`);
  }
  toc.push("");
}

const visible = capabilities.commands.filter(({ variantOf }) => !variantOf);
const areaSections = capabilities.areas.flatMap((area) => [
  `### ${area.title}`,
  "",
  area.summary,
  "",
  "| Command | Invocation | Purpose |",
  "| --- | --- | --- |",
  ...visible
    .filter((command) => command.area === area.id)
    .map(({ id, argv, purpose }) => `| \`${id}\` | \`${argv.join(" ")}\` | ${purpose} |`),
  ""
]);
const graph = capabilities.commands.find(({ id }) => id === "graph");
const views = capabilities.views.map(({ id, summary }) => `| \`${id}\` | ${summary} |`);
const formats = graph.options.format.enum.map((format) => `- \`${format}\``);

const capabilityReference = [
  "# Generated CLI capabilities",
  "",
  "<!-- Generated by scripts/generate-docs.js. Do not edit this file. -->",
  "",
  `This page describes BC Atlas ${capabilities.version}.`,
  "Run `npm run docs` after a capability changes.",
  "",
  "## Commands by feature area",
  "",
  ...areaSections,
  "## Architecture views",
  "",
  "| View | Shows |",
  "| --- | --- |",
  ...views,
  "",
  "## Diagram formats",
  "",
  ...formats,
  "",
  "## Exit codes",
  "",
  `- Success: \`${capabilities.exitCodes.success}\``,
  `- Operation failure or failed check: \`${capabilities.exitCodes.operation}\``,
  `- Usage error: \`${capabilities.exitCodes.usage}\``,
  "",
  "For all options and examples, read the [CLI reference](../cli-reference.md).",
  ""
].join("\n");

const outputs = new Map([
  [path.join(docsRoot, "_TOC_.md"), toc.join("\n")],
  [path.join(docsRoot, "reference", "cli-capabilities.md"), capabilityReference]
]);

const check = process.argv.includes("--check");
for (const [file, content] of outputs) {
  if (check) {
    const current = await readFile(file, "utf8").catch(() => "");
    if (current !== content) {
      console.error(`${path.relative(root, file)} is out of date. Run npm run docs.`);
      process.exitCode = 1;
    }
    continue;
  }

  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, content, "utf8");
  console.log(`Wrote ${path.relative(root, file)}`);
}
